[package]
name = "parse_chg"
version = "0.1.0"
authors = ["Root"]
edition ="2018"

[dependencies]
nom = "^5"
byteorder = "^1.3"
arrayref = "^0.3.5"
serde = { version = "1.0", features = [ "derive" ] }
quick-xml = { version = "0.22", features = [ "serialize" ] }